ALTER TABLE public.habits
ADD COLUMN IF NOT EXISTS created_at BIGINT,
ADD COLUMN IF NOT EXISTS archived_at BIGINT,
ADD COLUMN IF NOT EXISTS sealed_at BIGINT,
ADD COLUMN IF NOT EXISTS drops_claimed JSONB DEFAULT '{}'::jsonb;
