ALTER TABLE public.tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.habits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_quests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_boss DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.shared_music DISABLE ROW LEVEL SECURITY;
