ALTER TABLE public.tasks
ADD COLUMN status TEXT DEFAULT 'idle',
ADD COLUMN deadline BIGINT,
ADD COLUMN created_by TEXT,
ADD COLUMN assignee_name TEXT,
ADD COLUMN assignee_photo TEXT,
ADD COLUMN timer_type TEXT DEFAULT 'stopwatch',
ADD COLUMN limit_time BIGINT,
ADD COLUMN total_tracked_time BIGINT DEFAULT 0,
ADD COLUMN last_start_time BIGINT,
ADD COLUMN last_heartbeat BIGINT,
ADD COLUMN is_automated BOOLEAN DEFAULT false,
ADD COLUMN sub_tasks JSONB DEFAULT '[]'::jsonb,
ADD COLUMN auto_pause_reason TEXT,
ADD COLUMN current_worker TEXT,
ADD COLUMN current_worker_name TEXT,
ADD COLUMN auto_paused_at BIGINT,
ADD COLUMN end_time BIGINT,
ADD COLUMN scheduled_start_time BIGINT,
ADD COLUMN scheduled_end_time BIGINT,
ADD COLUMN calendar_event_id TEXT;
